export default {
  iczomicon: require('../assets/images/zomicon.jpg'),
  icGoogle: require('../assets/images/Google_logo.png'),
  icWest_Back: require('../assets/images/west_black.png'),
  icMOre: require('../assets/images/more_horz.png'),
  icclose: require('../assets/images/close_black.png'),
  icFacbook: require('../assets/images/facebook.png'),
  icEmail: require('../assets/images/email.png'),
  icDelivery: require('../assets/images/delivery.png'),
  icwallet: require('../assets/images/wallet.png'),
  icdinner: require('../assets/images/dinner.png'),
  icblinkit: require('../assets/images/Blinkit.jpg'),
  icLocation: require('../assets/images/Location.png'),
  icarrow_more: require('../assets/images/expand_more.png'),
  icTranslate: require('../assets/images/language-icon.png'),
  icProfile: require('../assets/images/profile.jpg'),
  icmic: require('../assets/images/mic.png'),
  icsreach: require('../assets/images/search.png'),
};
