export default {
  Food_Delivery: "India's #1 Food Delivery",
  Dining_App: ' and Dining App',
  Log_Sign: 'Log in or sign up',
  Phone_Number: 'Enter Phone Number',
  continue: 'Continue',
  or: 'or',
  agree_Our: 'By contining you agree to our ',
  Services_privacy: 'Terms of Service Privacy and Policy Content Policy',
  OTPSCREEN: 'OTP Vertification',
  Verification: 'We have sent a Verification code to',
  facebook: 'Continue with Facebook',
  Email: 'Continue with Email',
  Resendsms: 'Resend SMS in ',
  login_methods: 'Try other login methods',
  Dining: 'Dining',
  Delivery: 'Delivery',
  Money: 'Money',
  BottomTab: 'BottomTab',
  Bulidingloc: ' CDCL Building',
  sector: ' 28B,sector 28,Chandigharh',
  Restaurant: 'Restaurant or name dish..',
  sreach_Restaurant: 'Sreach restaurants',
  Recommend: 'RECOMMENDED FOR YOU',
  offper: '50% OFF',
  uptoOff: 'Up to ₹100',
  fortyoff: '40% OFF',
  uptoEighty: 'Up to ₹80',
  sixtyoff: '60% OFF',
  uptoTwenty: 'Up to ₹120',
  La_pinoz: "la _Pino'z",
  Pizza: 'Pizza',
  timing: '20-30 min',
  bhel: 'StreetShop',
  Street: 'Street Food',
  times: '10-20 min',
  clocktime: '30-40 min',
  NewSweets: 'PannaSweet',
  northIndian: 'North Indian',
  Pal_Dabba: 'Pal Dabba',
  Verka_Express: 'PunjabiDhab',
  Bakingo: 'Bakingo',
  Bakery: 'Bakery',
  National: 'National',
  Home_Dinners: 'HomeDinner',
  Explore: 'EXPLORE',
  Gourmet: 'Gourmet',
  Healthy: 'Healthy',
  Selections: 'Selections',
  Curated_dishes: 'Curated dishes',
  offers: 'Offers',
  flatdiscount: '60% Flat Discount',
  What_On_Your_MIND: "WHAT'S ON YOUR MIND?",
  Burger: 'Burger',
  Pizza: 'Pizza',
  Shake: 'Shake',
  VegThali: 'VegThali',
  Noodles: 'Noodles',
  Roll: 'Roll',
  Chiken: 'Chiken',
  Cakes: 'Cake',
  Biryani: 'Biryani',
  Samosa: 'Samosa',
  All_Restaurants: 'ALL RESTAURANTS',
  Sort: 'Sort',
  Likes: 'Likes',
  Award_winners: 'Award Winners',
  Nearest: 'Nearest',
  Great_offers: 'Great Offers',
  Rating: 'Rating 4.0+',
  Previously_Ordered: 'Previously Ordered',
  Pure_Veg: 'Pure Veg',
  Cuisines: 'Cuisines',
  Panner: 'Panner',
  Paratha: 'Paratha',
  Sandwich: 'SandWich',
  SouthIndian: 'SouthIndian',
  RestaurantsDelivery: '851 restaurants delivery to you',
  Featured: 'FEATURED',
  RestaurantName_Captain: "Captain Sam's",
  price_Food: 'Pizza. Fast Food . ₹550 for one',
  timing_delivery: '30-35 min . 2 km .',
  rating: '4.2',
  get_all_items: 'Get all items @ ₹219 only',
  offPer: '60% OFF  up to ₹120 Only',
  for_delicious: 'Delicious',
  RestaurantName_Nand: 'Nand Sweets',
  Mithai: 'Mithai . Street Food . ₹100 for one',
  Deliverytime: '35-40 min . 5 km .',
  Free_delivery: 'Free Delivery',
  Rating: 'Rating 4.1',
  KataniDhaba: 'Katani Dhaba',
  Skip: 'Skip',
  cancel: 'Cancel',
  English: 'English',
  hindi: 'हिंदी',
  Punjabi: 'ਪੰਜਾਬੀ',
  telgu: 'తెలుగు',
  tamil: 'தமிழ்',
  mrathi: 'मराठी',
  Nepali: 'नेपाली',
  Name: 'sheetal',
  ViewProfile: 'View  activity',
  percentage: '32%',
  Likes: 'Likes',
  Payments: 'Payments',
  Setting: 'Setting',
  App_Update_available: 'App Update available',
  Your_rating: 'Your rating',
  Food_Orders: 'Food Orders',
  orders: 'Your orders',
  Favorite_orders: 'Favorite orders',
  Address_Book: 'Address Book',
  Hidden_Restaurants: 'Hidden Restaurants',
  Food_ordering_help: 'Food ordering help',
  Grocery_ordering: 'Grocery ordering help',
  Deal_tansaction: 'Your deal & transactions',
  Dining_reward: 'Your Dining rewards',
  Slot_booking: 'Your slot Bookings',
  Dining_help: 'Dining help',
  slot_help: 'Slot booking help',
  Frequently_ques: 'Frequently asked questions',
  Games: 'Games',
  Zomato_Prediction: 'Zomato Prediction League 2023',
  Restaurant_Awards: 'Restaurant Awards 2023',
  Wining_restaurants: 'Wining restaurants',
  Zomato_Gold: 'Zomato Gold',
  Grocery_Orders: 'Grocery Orders',
  Dining: 'Dining',
  Events_tickets: 'Your event tickets',
  Evnet_help: 'Event_help',
  Buy_gift: 'Buy Gift Card',
  Claim_gift: 'Claim Gift Card',
  Gift_CardOrder: 'Gift Card order history',
  Zomato_credits: 'Zomato Credits',
  Gift_Card_help: 'Gift Card help',
  Money: 'MONEY',
  Zomato_wallet: 'Zomato Wallet',
  Choose_Lang: 'Choose Language',
  About: 'About',
  Send_Feedback: 'Send feedback',
  Get_receipt: 'Get Feeding India receipt',
  Emergency: 'Report a safety emergency',
  Logout: 'Log out',
  More: 'More',
  Filters: 'Filters',
  Delights: 'Delights',
  Book_Table: 'Book_Table',
  Outdoor_Seating: 'Outdoor_Seating',
  Serves_Alcohol: 'Serves_Alcohol',
  Open_Now: 'Open_Now',
  Cafe: 'Cafes',
  Fine_Dining: 'Fine_Dining',
  Restaurant_suggestion: 'RESTAURANT SUGGESTIONS',
  picked_foodies: 'Picked by top foodies',
  Zeek: 'Zeek',
  The_Brew_Estate: 'The Brew Estate',
  FlatForty: 'Flat 40% OFF',
  OFFWithBankOff: '15% OFF with bank off...',
  Flatthirty: 'Flat 35% OFF',
  FlatTWEnty: 'Flat 25% OFF',
  Roadies_Koffeeh: 'Roadies_Koffeeh...',
  Kakuna: 'Kakuna - A Culin...',
  Prankster: 'Prankster',
  The_Chocolate: 'The Chocolate R...',
  Qizo: 'Qizo',
  Boulevard: '26  Boulevard',
  What_LOoking: 'WHAT ARE YOU LOOKING FOR?',
  Newly_Open: 'Newly Opened',
  NightLife_Drinks: 'NightLife & Drinks',
  Famliy_Dining: 'Famliy_Dining',
  Romatic_Places: 'Romatic Places',
  Events: 'Events',
  Premium_Dining: 'Premium Dining',
  Must_TRIES: 'MUST TRIES IN CHANDIGARH',
  Best_intsa: ' 8 Best Insta-Worthly Places',
  Winners_Aaward: 'Winners Restaurant Awards',
  New_opend: '8 Newly Opened Restaurants',
  BarPubs: '8 Best Bars & Pubs',
  Breakfast: '7 Blissful Breakfast Places',
  Cuisiness: '7 Places for World Cuisines',
  Explore: 'Explore more',
  AVAILABLE_bANK: 'AVAILABLE BANK OFFERS',
  POPULAR_AROUND: ' POPULAR RESTAURANTS AROUND',
  Bar_Food: 'Bar Food . North Indian . Mughali',
  Peddlers: 'Peddlers',
  EXtra_offer: 'Extra bank Offers + up to 100% CashBack',
  Hotel_Heritage: 'Hotel Heritage,Sector 35,Chandigarh',
  Time: '2.7 Km',
  Add_credits: 'Add to your Zomato Credits',
  Zomato_credits: 'Zomato_Credits',
  Balance: 'Balance ₹0.00',
  PurchaseHistory: 'Purchase History',
  GIFT_CARDS: 'GIFT CARDS',
  Starting: 'Starting ₹100',
  Buy_share_instantly: 'Buy share & instantly',
  year_Validity: '1 year Validity',
  Buy_now: 'Buy now',
  WALLET: 'WALLET',
  Zomato_Wallet: 'Zomato Wallet',
  Zero_payment_Failures: 'Zero payment Failures',
  Activate_Wallet: 'Activate Wallet',
  MONEY: 'MONEY',
  By_Zomato: 'By Zomato',
  GIFT_CARDS_UPI: ' GIFT CARDS . WALLET . UPI and more..',
  addcart:"ADD +",
  Cart:"Cart",
  Item_ADD:"Item ADD",
  Next:"Next",
  Remove: "Remove",
  


  
};
