export default {
  Food_Delivery: "India's #1 Food Delivery",
  Dining_App: ' and Dining App',
  Log_Sign: 'Log in or sign up',
  Phone_Number: 'Enter Phone Number',
  continue: 'Continue',
  or: 'or',
  agree_Our: 'By contining you agree to our ',
  Services_privacy: 'Terms of Service Privacy and Policy Content Policy',
  OTPSCREEN: 'OTP Vertification',
  Verification: 'We have sent a Verification code to',
  facebook: 'Continue with Facebook',
  Email: 'Continue with Email',
  Resendsms: 'Resend SMS in ',
  login_methods: 'Try other login methods',
  Dining: 'Dining',
  Delivery: 'Delivery',
  Money: 'Money',
  BottomTab: 'BottomTab',
  Bulidingloc: ' CDCL Building',
  sector: ' 28B,sector 28,Chandigharh',
  Restaurant: 'Restaurant or name dish..',
  Recommend: 'RECOMMENDED FOR YOU',
  offper: '50% OFF',
  uptoOff: 'Up to ₹100',
  offper: '50% OFF',
  uptoOff: 'Up to ₹100',
  fortyoff: '40% OFF',
  uptoEighty: 'Up to ₹80',
  sixtyoff: '60% OFF',
  uptoTwenty: 'Up to ₹120',
  La_pinoz: "la _Pino'z",
  Pizza: 'Pizza',
  timing: '20-30 min',
  bhel: 'StreetShop',
  Street: 'Street Food',
  times: '10-20 min',
  clocktime: '30-40 min',
  NewSweets: 'PannaSweet',
  northIndian: 'North Indian',
  Pal_Dabba: 'Pal Dabba',
  Verka_Express: 'PunjabiDhab',
  Bakingo: 'Bakingo',
  Bakery: 'Bakery',
  National: 'National',
  Home_Dinners: 'HomeDinner',
  Explore: 'EXPLORE',
  Gourmet: 'Gourmet',
  Healthy: 'Healthy',
  Selections: 'Selections',
  Curated_dishes: 'Curated dishes',
  offers: 'Offers',
  flatdiscount: '60% Flat Discount',
  What_On_Your_MIND: "WHAT'S ON YOUR MIND?",
  Burger: 'Burger',
  Pizza: 'Pizza',
  Shake: 'Shake',
  VegThali: 'VegThali',
  Noodles: 'Noodles',
  Roll: 'Roll',
  Chiken: 'Chiken',
  Cakes: 'Cake',
  Biryani: 'Biryani',
  Samosa: 'Samosa',
  All_Restaurants: 'ALL RESTAURANTS',
  Sort: 'Sort',
  Likes: 'Likes',
  Award_winners: 'Award Winners',
  Nearest: 'Nearest',
  Great_offers: 'Great Offers',
  Rating: 'Rating 4.0+',
  Previously_Ordered: 'Previously Ordered',
  Pure_Veg: 'Pure Veg',
  Cuisines: 'Cuisines',
  Panner: 'Panner',
  Paratha: 'Paratha',
  Sandwich: 'SandWich',
  SouthIndian: 'SouthIndian',
  RestaurantsDelivery: '851 restaurants delivery to you',
  Featured: 'FEATURED',
  RestaurantName_Captain: "Captain Sam's",
  price_Food: 'Pizza. Fast Food . ₹550 for one',
  timing_delivery: '30-35 min . 2 km .',
  rating: '4.2',
  get_all_items: 'Get all items @ ₹219 only',
  offPer: '60% OFF  up to ₹120 Only',
  for_delicious: 'Delicious',
  RestaurantName_Nand: 'Nand Sweets',
  Mithai: 'Mithai . Street Food . ₹100 for one',
  Deliverytime: '35-40 min . 5 km .',
  Free_delivery: 'Free Delivery',
  Rating: '4.1',
  KataniDhaba: 'Katani Dhaba',
  Skip: 'Skip',
  cancel: 'Cancel',
  English: 'English',
  hindi: 'हिंदी',
  Punjabi: 'ਪੰਜਾਬੀ',
  telgu: 'తెలుగు',
  tamil: 'தமிழ்',
  mrathi: 'मराठी',
  Nepali: 'नेपाली',
  Name: 'sheetal',
  ViewProfile: 'View  activity',
  percentage: '32%',
  Likes: 'Likes',
  Payments: 'Payments',
  Setting: 'Setting',
  App_Update_available: 'App Update available',
  Your_rating: 'Your rating',
  Food_Orders: 'Food Orders',
  orders: 'Your orders',
  Favorite_orders: 'Favorite orders',
  Address_Book: 'Address Book',
  Hidden_Restaurants: 'Hidden Restaurants',
  Food_ordering_help: 'Food ordering help',
  Grocery_ordering: 'Grocery ordering help',
  Deal_tansaction: 'Your deal & transactions',
  Dining_reward: 'Your Dining rewards',
  Slot_booking: 'Your slot Bookings',
  Dining_help: 'Dining help',
  slot_help: 'Slot booking help',
  Frequently_ques: 'Frequently asked questions',
  Games: 'Games',
  Zomato_Prediction: 'Zomato Prediction League 2023',
  Restaurant_Awards: 'Restaurant Awards 2023',
  Wining_restaurants: 'Wining restaurants',
  Zomato_Gold: 'Zomato Gold',
  Grocery_Orders: 'Grocery Orders',
  Dining: 'Dining',
  Events_tickets: 'Your event tickets',
  Evnet_help: 'Event_help',
  Buy_gift: 'Buy Gift Card',
  Claim_gift: 'Claim Gift Card',
  Gift_CardOrder: 'Gift Card order history',
  Zomato_credits: 'Zomato Credits',
  Gift_Card_help: 'Gift Card help',
  Money:"Money",
  Zomato_wallet:"Zomato Wallet",
  Choose_Lang:"Choose Language",
  About:"About",
  Send_Feedback:"Send feedback",
  Get_receipt:"Get Feeding India receipt",
  Emergency:"Report a safety emergency",
  Logout:"Log out",
  More:"More"
};
